export type Lang = "id" | "en";

export const COPY = {
  id: {
    brand: "Cloud in Asia",
    brandGuide: "Guide",
    navLearn: "Belajar",
    navOverview: "Beranda",
    navBuildings: "Pusat Data",
    navTech: "Teknologi",
    navAbout: "Tentang",
    navUpdates: "Pembaruan",
    navMore: "Lainnya",
    navMenu: "Menu",
    navClose: "Tutup",
    navMainSite: "CloudinAsia",
    navMainSiteAria: "Situs utama CloudinAsia",
    navFlow: "Cara pakai",
    navLaw: "Regulasi",
    navOss: "Kenapa open source",
    navPath: "Pilih jalur",
    navData: "Yang lokal",
    navLook: "Tampilan",
    foot: "Cloud Directory ASEAN — produk editorial CloudinAsia. Bukan nasihat hukum.",
    kicker: "Cloud in Asia Cloud Directory",
    h1: "Cari cloud yang cocok tanpa harus jadi ahli cloud dulu",
    h1a: "Cari cloud yang cocok",
    h1b: "tanpa harus jadi ahli cloud dulu",
    lede: "Ceritakan apa yang mau Anda jalankan. Kami pecah jadi pertanyaan yang lebih berguna: data tinggal di mana, siapa yang pegang akses, bagaimana backup-nya, berapa biayanya, dan seberapa mudah pindah kalau suatu hari perlu.",
    trustNote: "Berdasarkan sumber publik. Untuk screening awal, bukan keputusan legal atau endorsement.",
    scoreDisclaimer: "Indikator untuk membantu screening, bukan sertifikat.",
    riskBannerUs:
      "Kota DC di ASEAN tidak meniadakan CLOUD Act. Otoritas AS masih bisa memaksa operator AS. Residensi data bukan kontrol hukum.",
    riskBannerCn:
      "Kota DC di ASEAN tidak meniadakan hukum siber Tiongkok (CSL/PIPL). Residensi data bukan kontrol hukum.",
    factLocal: "penyedia berkantor di ASEAN",
    factAll: "semua di basis data",
    factTiers: "paket yang tercatat",
    factOss: "menyebut KVM / Proxmox / Xen",
    factBuildings: "fasilitas bernama",
    flowKicker: "Cara pakai",
    flowH2: "Jangan mulai dari merek. Mulai dari masalah yang mau diselesaikan.",
    flowSub:
      "Website publik, sistem akademik, aplikasi transaksi, dan layanan pemerintah tidak punya checklist yang sama. Cloud untuk website kampus, transaksi keuangan, aplikasi pemerintah, dan eksperimen AI jelas beda.",
    flow1t: "Ceritakan kebutuhannya",
    flow1: "Apa yang mau dijalankan? Seberapa fatal kalau down? Datanya sensitif atau biasa? Harus tinggal di negara tertentu?",
    flow2t: "Lihat buktinya",
    flow2: "Kami bedakan mana yang terverifikasi, mana klaim penyedia, mana inferensi, dan mana yang memang belum diketahui.",
    flow3t: "Bandingkan beberapa kandidat",
    flow3: "Tidak perlu 30 tab browser. Ambil 2–4 kandidat, lalu bawa pertanyaan yang belum terjawab ke vendor dan tim internal.",
    lawKicker: "Regulasi",
    lawH2: "Regulasi lintas negara: titik awal, bukan keputusan akhir",
    lawSub:
      "Lokasi server hanyalah satu bagian dari kepatuhan. Jenis data, sektor, entitas kontrak, subprocessor, dan alur transfer dapat mengubah kewajiban Anda.",
    lawBanner:
      "Ringkasan ini adalah pengantar editorial, bukan nasihat hukum. Kewajiban Anda bergantung pada jenis data, sektor, entitas kontrak, tujuan pemrosesan, subprocessor, dan mekanisme transfer. Tinjau sumber resmi dan konsultasikan legal/compliance sebelum keputusan produksi.",
    lawReview: "Perlu verifikasi sumber resmi dan tanggal tinjauan.",
    lawIdT: "Indonesia · UU No. 27 Tahun 2022 tentang Pelindungan Data Pribadi",
    lawId1:
      "Pasal 56 mengatur transfer data pribadi ke luar wilayah hukum Indonesia melalui persyaratan tertentu. Lokasi server saja tidak cukup untuk menilai kepatuhan; periksa pengendali/prosesor, tujuan transfer, mekanisme perlindungan, dan aturan sektoral yang berlaku.",
    lawId2:
      "Status: pengantar editorial. Verifikasi aturan pelaksana dan perkembangan terbaru sebelum dipakai untuk keputusan.",
    lawSg:
      "Organisasi yang mentransfer personal data ke luar Singapore tetap memiliki kewajiban perlindungan yang sebanding sesuai aturan transfer yang berlaku. Lokasi data center di Singapore tidak otomatis memenuhi kewajiban negara lain.",
    lawMy:
      "Kewajiban transfer lintas batas dan data localization dapat berbeda menurut aturan, sektor, dan jenis data. Hindari klaim umum tanpa menunjuk dasar hukum dan cakupannya.",
    lawTh:
      "Transfer lintas batas dan perlindungan personal data perlu dinilai berdasarkan ketentuan yang berlaku, peran organisasi, dan mekanisme perlindungan. Region Bangkok bukan bukti kepatuhan untuk seluruh ASEAN.",
    lawPh:
      "Tanggung jawab organisasi tidak berhenti pada lokasi server. Periksa pengendali/prosesor, kontrak, pengamanan, kewajiban kebocoran, dan transfer yang relevan.",
    lawVn:
      "Persyaratan pemrosesan, transfer lintas batas, dan kemungkinan data localization perlu merujuk pada instrumen hukum yang berlaku saat publikasi. Jangan memakai label tahun tanpa nama aturan dan tanggal berlaku yang terverifikasi.",
    lawAsean:
      "Kerangka ASEAN dapat membantu interoperabilitas, tetapi kewajiban hukum tetap bergantung pada negara, sektor, kontrak, dan alur data yang terlibat.",
    lawNone: "Tidak ada UU bersama",
    ossKicker: "Teknologinya",
    ossH2: "Teknologi terbuka memberi lebih banyak pilihan. Bukan jaminan otomatis.",
    ossSub:
      "Open source dan open standards bisa membuat sistem lebih mudah diaudit, dipahami, dan dipindahkan. Source code terbuka tidak otomatis membuat layanan aman atau patuh. Yang tetap harus dicek: konfigurasi, akses operator, kontrak, kompetensi tim, lokasi data, dan yurisdiksi. {n} penyedia di dataset ini menyebut KVM, Proxmox, Xen, atau OpenStack.",
    oss1t: "Bisa dilihat",
    oss1:
      "KVM, Kubernetes, Ceph, dan banyak proyek open source punya kode yang dapat diperiksa. Artinya Anda tidak harus percaya penuh pada brosur vendor.",
    oss2t: "Bisa pindah",
    oss2:
      "API dan format terbuka biasanya membuat migrasi lebih masuk akal. Pertanyaannya bukan cuma bisa deploy, tetapi juga bisa keluar tanpa membangun ulang semuanya.",
    oss3t: "Siapa yang pencet tombol",
    oss3:
      "Lokasi data center hanyalah salah satu bagian. Kalau panel, akses administrator, atau proses operasional penting masih bergantung pada pihak lain, kontrolnya juga perlu dihitung.",
    pathKicker: "Pilih jalur",
    pathH2: "Mulai dari kebutuhan, bukan dari merek",
    path1t: "Data harus di negara saya",
    path1:
      "Kota DC tertulis di ASEAN, badan hukum yang jelas, dan gedung yang bisa dicek. Merek lokal tanpa lokasi bukan otomatis tinggi.",
    path1go: "Lihat penyedia lokal",
    path2t: "Sistem terbuka, jangan terkunci",
    path2:
      "KVM/Xen, Kubernetes, Ceph. Yang tidak menyebutkan hypervisor dianggap belum jelas, bukan nol.",
    path2go: "Pelajari teknologinya",
    path3t: "Lokal, tapi masuk anggaran",
    path3:
      "Bandingkan harga hanya di antara cloud ASEAN. Murah di Frankfurt tidak menjawab di mana data tinggal.",
    path3go: "Bandingkan harga",
    dataKicker: "Dalam dataset ini",
    dataH2: "Penyedia dengan indikator kontrol lokal tertinggi",
    dataSub:
      "Urutan memakai metodologi yang sama untuk semua. Nilai menunjukkan kelengkapan indikator yang kami ukur—bukan sertifikat kepatuhan, keamanan, atau kualitas layanan.",
    filterAll: "Semua",
    filterCountry: "Negara",
    cityKicker: "Di mana data bisa tinggal",
    cityH2: "Kota pusat data yang relevan",
    citySub:
      "Bukan peta lingkaran. Ini kota tempat paketnya benar-benar tercatat. Jakarta lebih menentukan daripada Frankfurt.",
    cityProv: "penyedia",
    pkg: "paket",
    from: "dari",
    hvUnknown: "Not disclosed",
    navCompare: "Bandingkan",
    arenaKicker: "Perbandingan penyedia",
    arenaH1: "Jangan bandingkan semua cloud. Cari yang relevan dulu.",
    arenaLede:
      "Filter membantu mempersempit kandidat berdasarkan hal yang benar-benar penting. Setelah itu buka detailnya dan cek bukti di balik setiap indikator. Hasil adalah shortlist untuk investigasi lanjut, bukan rekomendasi final.",
    tabSov: "Kontrol & residensi",
    tabOss: "Open technology",
    tabCost: "Harga",
    tabCover: "Jangkauan",
    tabPerf: "Kapasitas",
    scopeAsean: "Berkantor di ASEAN",
    scopeAll: "Semua",
    colProvider: "Penyedia",
    colHq: "Kantor pusat",
    colHv: "Hypervisor",
    colMetric: "Catatan",
    colScore: "Indikator",
    scoreSov: "Indikator kontrol & residensi",
    scoreOss: "Indikator open technology",
    scoreCost: "Harga dari (USD)",
    scoreCover: "Jumlah lokasi DC",
    scorePerf: "vCPU terbesar",
    empty: "Belum ada bukti publik yang cukup untuk saringan ini.",
    nShown: "ditampilkan",
    navMethod: "Metodologi",
    methKicker: "Metodologi",
    methH1: "Skornya datang dari mana?",
    methLede:
      "Setiap indikator dibangun dari field yang bisa ditelusuri ke dataset dan sumbernya. Skor membantu membandingkan kandidat dengan cara yang konsisten. Skor bukan sertifikat keamanan, kepatuhan, atau kedaulatan.",
    methSovT: "Indikator kontrol & residensi data (0–100)",
    methSov1: "+40 residensi: kota DC ASEAN pada paket OK, atau kota resmi di halaman region. Kosong / Undisclosed / Not disclosed = 0",
    methSov2: "+25 kontrol hukum: HQ atau badan hukum di ASEAN",
    methSov3: "+15 tambahan: badan hukum ASEAN dan negara hukum = negara DC paket",
    methSov4: "+20 fasilitas: ada gedung listed dengan nama resmi",
    methSovNote:
      "Perusahaan lokal tanpa lokasi DC yang tertulis tidak otomatis tinggi. Rak di Jakarta milik operator AS bukan 100: data bisa di ASEAN, kontrol hukum tidak. Hypervisor terbuka masuk indikator open technology, bukan di sini.",
    methOssT: "Indikator open technology (0–100)",
    methOss5: "+15 control plane yang dapat dijalankan sendiri (Proxmox, OpenStack)",
    methOssNote:
      "Field yang tidak menyebut hypervisor tidak dihukum sebagai nol — dianggap belum terbukti. Open source dinilai karena bisa diaudit, bukan karena murah. Virtualizor tidak dihitung sebagai control plane terbuka.",
    methLimit:
      "Dataset masih sementara. Sebagian baris dari seed lama. Inferensi (likely/implied) tidak boleh dibaca sebagai fakta. Eropa murni tidak masuk default. Hyperscaler global hanya muncul pada saringan “Semua”.",
    methLawT: "Negara operator vs lokasi fasilitas",
    methLaw:
      "Risiko yurisdiksi mengikuti perusahaan dan hukum yang berlaku, bukan hanya kota DC. Perusahaan AS dapat tunduk pada CLOUD Act meski raknya di ASEAN. Operator Tiongkok tunduk hukum siber Tiongkok. Ini pengantar, bukan nasihat hukum.",
    methGo: "Buka perbandingan",
    provBack: "Kembali ke perbandingan",
    provSov: "Kontrol & residensi",
    provOss: "Open technology",
    bldgKicker: "Direktori fasilitas",
    bldgH1: "Data center-nya benar ada di mana?",
    bldgLede:
      "Kami mengumpulkan nama fasilitas, kota, operator, dan penyedia yang menyebut lokasi tersebut di sumber publik. Nama gedung adalah awal yang bagus. Satu pin di peta belum menjawab di mana seluruh data, backup, atau control plane berada.",
    bldgListed: "Fasilitas dengan bukti publik",
    bldgUnknownH1: "Lokasi fasilitas belum terverifikasi",
    bldgUnknownSub: "Penyedia menyebut area ini, tetapi nama gedung, operator, atau alamat belum dapat dikonfirmasi dari sumber publik.",
    bldgUnknownBody: "Catatan ini dipertahankan agar kekosongan data terlihat, bukan untuk menyatakan bahwa penyedia berada di fasilitas tertentu.",
    mapSov: "Kontrol & residensi",
    techH1: "Jangan cuma lihat harga. Lihat apa yang menjalankan cloud-nya.",
    techLede:
      "Hypervisor, storage, container runtime, dan control plane menentukan bagaimana sistem Anda berjalan, dipindah, dan dikelola. Di sini kami jelaskan teknologinya tanpa menganggap semua pembaca sudah hidup di terminal sejak lahir.",
    techNone: "Belum ada penyedia terverifikasi yang menulis teknologi ini dalam dataset ini.",
    aboutKicker: "Tentang CloudinAsia",
    aboutH1: "Cloud in Asia membantu orang memahami cloud sebelum membeli cloud",
    aboutLede:
      "Cloud in Asia adalah media dan ecosystem platform untuk industri cloud dan open technology di Asia. Cloud Directory membuat ekosistem itu lebih mudah dipahami: bukan dengan daftar logo, tetapi dengan data yang bisa ditelusuri.",
    about1t: "Tentang Cloud in Asia Cloud Directory",
    about1:
      "Direktori ini adalah produk editorial berbasis data untuk membantu pembaca memahami penyedia, lokasi pusat data, teknologi, harga, dan indikator kontrol data di Asia Tenggara. Bukan marketplace, sertifikasi kepatuhan, atau endorsement.",
    about2t: "Apa yang kami nilai—dan apa yang tidak",
    about2:
      "Kami membandingkan data yang dapat ditelusuri: entitas operator, lokasi fasilitas, pernyataan residensi, stack, paket, dan keterbukaan bukti. Kami tidak menyimpulkan keamanan, kualitas dukungan, kepatuhan, atau kelayakan workload hanya dari lokasi server atau jenis hypervisor.",
    about3t: "Open technology, tanpa menyederhanakan risiko",
    about3:
      "Open source dapat meningkatkan auditabilitas dan portabilitas, tetapi tidak otomatis membuat layanan aman, patuh, atau berdaulat. Hasilnya tetap bergantung pada arsitektur, operasi, akses, kontrak, dan yurisdiksi.",
    about4t: "Transparansi editorial",
    about4:
      "Setiap field idealnya memiliki sumber, tanggal pembaruan, dan status verifikasi. Hubungan komersial akan diungkapkan ketika relevan. Koreksi dapat diajukan. Ini bukan nasihat hukum.",
    methOss1: "+30 hypervisor KVM / Proxmox / Xen",
    methOss2: "+20 Docker atau Kubernetes",
    methOss3: "+20 penyimpanan Ceph / OpenEBS / Longhorn / Rook",
    methOss4: "+15 stack dinyatakan open source",
    methOtherT: "Harga, jangkauan, kapasitas",
    methOther:
      "Harga: estimasi per bulan dalam USD. Yang ditagih per jam dihitung 24 jam × 31 hari. Jangkauan: jumlah kota DC yang tercatat. Kapasitas: vCPU dan RAM terbesar di paket yang ada. Bandingkan di dalam ASEAN, bukan versus Hetzner.",
    methLimitT: "Batas jujur",
    provHq: "Kantor pusat",
    provLegal: "Yurisdiksi",
    riskUs: "CLOUD Act AS",
    riskCn: "hukum siber Tiongkok",
    provStack: "Stack",
    stackHv: "Hypervisor",
    stackOrch: "Orkestrasi",
    stackStor: "Storage",
    stackCp: "Control plane",
    stackRuntime: "Container runtime",
    provCities: "Kota DC",
    provPlans: "Paket",
    colPlan: "Paket",
    colCpu: "vCPU",
    colRam: "RAM",
    colDisk: "Disk",
    colPrice: "Harga",
    noPlans: "Belum ada paket di basis ini.",
    noProv: "Penyedia tidak ditemukan.",
    navMap: "Peta",
    bldgProviders: "Penyedia",
    bldgOperator: "Operator",
    bldgAddress: "Alamat",
    bldgInHere: "Penyedia di gedung ini",
    bldgBack: "Semua gedung",
    mapKicker: "Peta",
    mapH1: "Wilayah yang bisa diklik",
    mapLede:
      "Bukan pin. Klik negara, lalu kota, untuk melihat siapa yang tersedia. Dua mode: seberapa ramai, dan seberapa kuat kontrol & residensi.",
    mapPop: "Populasi penyedia",
    mapHintPop: "Makin pekat tosca-nya, makin banyak penyedia di wilayah itu.",
    mapHintSov: "Makin pekat tosca-nya, makin tinggi indikator kontrol & residensi rata-rata.",
    mapClick: "Klik negara, atau pin gedung DC.",
    mapCables: "Kabel laut",
    mapProviders: "Penyedia di sini",
    mapCities: "Kota",
    mapNone: "Belum ada penyedia tercatat di wilayah ini.",
    techKicker: "Teknologi",
    techBack: "Semua teknologi",
    techOpen: "Terbuka",
    techClosed: "Tertutup",
    techLicence: "Lisensi",
    techWhat: "Apa ini",
    techPlus: "Kelebihan",
    techMinus: "Kekurangan",
    techWho: "Penyedia yang mencatat teknologi ini",
    techPlans: "Contoh paket",
    techProviders: "Penyedia",
    navCorrect: "Koreksi",
    correctKicker: "Koreksi data",
    correctH1: "Laporkan data yang keliru atau kirim bukti baru",
    correctLede:
      "Direktori ini editorial. Kalau field salah, kedaluwarsa, atau ada sumber primer yang belum kami pakai, kirim bukti. Koreksi dicatat; kami tidak mengubah data hanya dari klaim tanpa tautan.",
    correctHow:
      "Sertakan: nama penyedia atau fasilitas, field yang dikoreksi, URL sumber primer, tanggal sumber, dan nama organisasi Anda. Jangan kirim data pelanggan atau rahasia dagang.",
    correctGo: "Buka CloudinAsia",
    methVerT: "Versi rumus",
    methVer:
      "Formula 2026.08.18. Indikator kontrol = residensi data 40 · kontrol hukum 40 · fasilitas bernama 20. Bukan nilai paspor perusahaan. Field kosong = 0, tidak dikurangi. Open technology dan kualitas bukti dihitung terpisah.",
    techVaried: "Bervariasi",
    techCountNote: "Jumlah berdasarkan field yang ditulis penyedia; inferensi tidak dihitung.",
    lastUpdated: "Dataset ditinjau 30 Agustus 2026",
    updKicker: "Log data",
    updH1: "Pembaruan Cloud Directory",
    updLede:
      "Penyedia yang baru ditemukan, plus penyedia lama yang datanya baru berubah. Setiap entri memakai tanggal dan jam WIB. Harga dan gedung hanya yang tertulis di situs resmi.",
    updEmpty: "Belum ada entri pembaruan.",
    updNew: "Baru ditemukan",
    updChanged: "Data diperbarui",
    scoreConf: "Kualitas bukti",
    evClaimed: "Dinyatakan penyedia",
    evInferred: "Terindikasi",
    evUnknown: "Belum diketahui",
    evVerified: "Terverifikasi",
    provEvidence: "Status bukti per field",
    fieldHq: "Kantor pusat",
    fieldHv: "Hypervisor",
    fieldSrc: "Sumber publik",
    fieldBldg: "Fasilitas bernama",
    fieldDc: "Negara DC pada paket",
    openSource: "Buka sumber",
    methConfBody:
      "Kualitas bukti: kantor pusat 20 · hypervisor dinyatakan 20 / terindikasi 10 · fasilitas bernama 15 · negara DC pada paket 15 · URL sumber 15 · yurisdiksi 15. Field kosong tidak dikurangi.",
    navStart: "Mulai",
    startKicker: "Kebutuhan awal",
    startH1: "Ceritakan kebutuhan cloud Anda",
    startLede: "Tidak perlu tahu semua istilah teknis. Jawab yang Anda tahu. Kalau ada yang belum jelas, kami ubah menjadi pertanyaan yang bisa Anda bawa ke tim atau penyedia cloud.",
    startPrivacy: "Jangan masukkan data rahasia, nama individu, nomor identitas, atau isi dokumen internal. Kategori umum sudah cukup.",
    startResultGo: "Lihat fokus perbandingan",
    qOrg: "Organisasi Anda paling mirip yang mana?",
    qOrgHelp: "Jawaban ini hanya membantu kami menyesuaikan pertanyaan berikutnya.",
    qWork: "Apa yang akan dijalankan di cloud?",
    qWorkHelp: "Pilih paling banyak tiga. Tidak perlu menjelaskan arsitektur.",
    qImpact: "Kalau layanan berhenti beberapa jam, dampaknya seperti apa?",
    qData: "Apakah sistem ini menyimpan data yang perlu dijaga lebih ketat?",
    qDataHelp: "Jika ragu, pilih belum tahu. Kami akan menambahkan klasifikasi data ke checklist.",
    qCountry: "Di negara mana mayoritas pengguna dan operasi Anda berada?",
    qPrio: "Apa yang paling penting dalam tahap awal ini? Pilih hingga tiga.",
    resultKicker: "Hasil screening",
    resultH1: "Ini fokus perbandingan Anda—bukan keputusan final",
    resultPri: "Prioritas Anda",
    resultUnk: "Masih perlu diketahui",
    resultUnkNone: "Tidak ada jawaban yang dilewati pada pertanyaan inti.",
    resultVal: "Perlu divalidasi oleh tim terkait",
    resultCheck: "Checklist ke penyedia",
    resultShort: "Shortlist untuk dicek",
    resultShortHelp: "2–4 kandidat dari jawaban Anda. Bukan ranking merek dan bukan sertifikat kepatuhan.",
    resultCompare: "Bandingkan shortlist ini",
    resultArena: "Lihat daftar lengkap",
    resultEdit: "Ubah jawaban",
    resultClear: "Hapus jawaban saya",
    resultSaved: "Jawaban tersimpan di perangkat ini.",
    screenBanner: "Ini shortlist untuk investigasi lanjut, bukan penilaian kepatuhan. Bawa ke tim yang memahami sektor dan yurisdiksi Anda.",
    heroCta: "Mulai dari kebutuhan",
    heroCta2: "Saya sudah tahu kriterianya",
    conceptKicker: "Lima konsep",
    conceptH2: "Lima pertanyaan sebelum nama penyedia",
    concept1t: "Data saya sebenarnya tinggal di mana?",
    concept1: "Jangan cuma lihat lokasi server utama. Backup, log, metadata, dan salinan lain bisa tinggal di tempat berbeda.",
    concept2t: "Kalau ada masalah, saya berurusan dengan siapa?",
    concept2: "Merek produk dan perusahaan yang menandatangani kontrak belum tentu sama. Ini penting saat bicara dukungan, sengketa, dan yurisdiksi.",
    concept3t: "Siapa yang punya tombol admin?",
    concept3: "Server boleh lokal. Sistem pengelolaannya belum tentu lokal. Cari tahu siapa yang bisa mengakses, mengubah, mematikan, atau mengekspor sistem Anda.",
    concept4t: "Kalau besok mau pindah, bisa?",
    concept4: "Cek format data, API, backup, biaya keluar, dan seberapa banyak pekerjaan manual yang dibutuhkan. Masuk cloud biasanya mudah. Rencana keluar justru sering dilupakan.",
    concept5t: "Klaimnya bisa dibuktikan?",
    concept5: "Secure, sovereign, enterprise, dan compliant adalah kata yang mudah ditulis. Yang lebih penting: sumbernya apa, tanggalnya kapan, dan apa yang sebenarnya dibuktikan?",
    whyShown: "Kenapa muncul di hasil ini",
    needConfirm: "Masih perlu ditanya",
    addCompare: "Tambahkan ke perbandingan",
    inCompare: "Dalam perbandingan",
    compareNav: "Bandingkan",
    compareH1: "Bandingkan yang diketahui—dan yang masih perlu ditanya",
    compareEmpty: "Pilih 2–4 penyedia dari daftar. Ini shortlist untuk divalidasi, bukan rekomendasi final.",
    unknownHint: "Not disclosed",
    beginnerKnown: "Yang dapat diketahui dari sumber publik",
    beginnerUnknown: "Yang belum cukup jelas",
    ossPolicyH2: "Open source di ASEAN: yang terverifikasi, yang historis",
    ossPolicySub: "Tidak ada mandat OSS horizontal ASEAN yang terverifikasi dari sumber resmi yang ditinjau. Pertanyaannya: kontrol, bukti, kontrak, lokasi data, dukungan, dan rencana keluar apa yang harus dapat ditunjukkan?",
    lawVnT: "Vietnam · Decree 13/2023/ND-CP",
    lawOssBadge: "Sumber resmi ditinjau 17 Agu 2026 · Status dapat berubah · Bukan penilaian kepatuhan",
    bldgNoPhoto: "Belum ada foto publik terverifikasi untuk fasilitas ini. Kami tidak mengisi dengan foto stok.",
    bldgPhotoSrc: "Sumber foto",
    techOrigin: "Asal",
    techSteward: "Pengelola",
    techEnterprise: "Enterprise",
    techEntYes: "Ada",
    techEntNo: "Tidak ada SKU terpisah",
    techEntIndirect: "Tidak dijual terpisah",
    chipLocal: "Lokal ASEAN",
    chipGlobal: "Global",
    chipAsk: "Bukti masih tipis",
    footBlurb: "Cloud Directory membantu membandingkan penyedia, lokasi data, dan stack yang bisa ditelusuri. Bukan sertifikat kepatuhan.",
    footExplore: "Jelajah",
    footAbout: "Editorial",
    footSource: "Kode terbuka",
    footGithub: "Lihat di GitHub",
    footLicense: "Dataset dan metode bisa ditinjau. Pull request dan koreksi diterima.",
    undisclosedBuilding: "Undisclosed building",
  },
  en: {
    brand: "Cloud in Asia",
    brandGuide: "Guide",
    navLearn: "Learn",
    navOverview: "Home",
    navBuildings: "Data Centres",
    navTech: "Technology",
    navAbout: "About",
    navUpdates: "Updates",
    navMore: "More",
    navMenu: "Menu",
    navClose: "Close",
    navMainSite: "CloudinAsia",
    navMainSiteAria: "CloudinAsia main site",
    navFlow: "How it works",
    navLaw: "Regulation",
    navOss: "Why open source",
    navPath: "Pick a path",
    navData: "Local picks",
    navLook: "Display",
    foot: "ASEAN Cloud Directory — an editorial product of CloudinAsia. Not legal advice.",
    kicker: "Cloud in Asia Cloud Directory",
    h1: "Find a cloud that fits your need",
    h1a: "Find a cloud that fits",
    h1b: "without becoming a cloud expert first",
    lede: "Tell us briefly what you want to run. We help turn that into data location, access, backup, cost, support, portability and evidence quality.",
    trustNote: "Based on public sources · Unknowns stay visible · Education and first screening, not legal advice or an endorsement",
    scoreDisclaimer: "A screening indicator, not a compliance certificate.",
    riskBannerUs:
      "An ASEAN DC city does not cancel the CLOUD Act. US authorities can still compel a US operator. Data residency is not legal control.",
    riskBannerCn:
      "An ASEAN DC city does not cancel China’s cyber laws (CSL/PIPL). Data residency is not legal control.",
    factLocal: "providers headquartered in ASEAN",
    factOss: "mention KVM / Proxmox / Xen",
    factBuildings: "named facilities",
    factAll: "in the database",
    factTiers: "recorded plans",
    flowKicker: "How it works",
    flowH2: "Do not start from a brand. Start from the problem you need solved.",
    flowSub:
      "A public website, an academic system, a payments app and a government service do not need the same checklist.",
    flow1t: "Describe the situation",
    flow1: "Workload, outage impact, data type, country and priorities.",
    flow2t: "Check the evidence",
    flow2: "Separate verified sources, provider statements, inferences and unknowns.",
    flow3t: "Build a shortlist",
    flow3: "Compare 2–4 providers, then take the important questions to your team and the vendor.",
    lawKicker: "The rules",
    lawH2: "Every ASEAN country has its own law",
    lawSub:
      "Picking a local cloud is not taste. If you store people’s data, sending it abroad has conditions. A Jakarta server is not enough if someone else runs the controls.",
    lawIdT: "Personal Data Protection Law",
    lawId1:
      "Transfers inside Indonesia are fine. Sending data abroad (Article 56) needs equivalent protection in the destination — or a binding safeguard. That is why local HQ plus local DC count, not just a rack address.",
    lawId2:
      "Older transfer rules are still used by agencies. “We have a box in Cibitung” is not the same as data staying in-country.",
    lawSg:
      "More open on outbound transfers. Newer rules add DPOs and breach notice. A Singapore DC does not satisfy Indonesia’s PDP Law on its own.",
    lawMy:
      "Some data must stay in-country. Right for Malaysian workloads, not a substitute for Indonesian residency.",
    lawTh:
      "In full force since 2022, close to GDPR. A Bangkok DC helps Thai work. It is not an “ASEAN-wide pass”.",
    lawPh:
      "Broad coverage and breach notice. Pick a clear jurisdiction and a complaints path, not just a Manila price.",
    lawVn:
      "“Core” or “important” data is hard to send abroad. For Vietnamese work, keep the controller in-country.",
    lawAsean:
      "The ASEAN PDP framework is guidance, not a statute. Complying in one country does not clear the others.",
    lawNone: "No shared ASEAN act",
    ossKicker: "The stack",
    ossH2: "Open technology can help you understand and move a system",
    ossSub:
      "{n} providers here say they run KVM, Proxmox, Xen, or OpenStack. That is not a medal. It means you can inspect. Closed stacks can be legal — you just have to take their word.",
    oss1t: "You can look",
    oss1:
      "KVM, Xen, Ceph, Kubernetes, Longhorn: your team can read the code. VMware or a closed panel: you depend on the vendor and its courts.",
    oss2t: "You can leave",
    oss2:
      "Open formats and APIs make switching easier. A closed stack turns year-two pricing into a vendor problem, not a technical one.",
    oss3t: "Who presses the button",
    oss3:
      "A local DC with a foreign panel is still foreign. Open source lets the control plane run on home soil. That is how Article 56 meets the hypervisor.",
    pathKicker: "Pick a path",
    pathH2: "Start from the need, not the brand",
    path1t: "Data must stay in my country",
    path1:
      "A named ASEAN DC city, a clear legal home, and a hall you can check. A local brand with no location is not automatically high.",
    path1go: "See local providers",
    path2t: "Open stack, no lock-in",
    path2:
      "KVM/Xen, Kubernetes, Ceph. Unstated hypervisors are incomplete, not zero.",
    path2go: "See the hypervisor column",
    path3t: "Local, and on budget",
    path3:
      "Compare prices only among ASEAN clouds. Cheap in Frankfurt does not answer residency.",
    path3go: "See starting prices",
    dataKicker: "In this dataset",
    dataH2: "Local ASEAN providers",
    dataSub:
      "Sorted by named ASEAN DC city, legal home, and a listed hall. Scores are a screen, not a certificate.",
    filterAll: "All",
    filterCountry: "Country",
    cityKicker: "Where the data can live",
    cityH2: "Data-centre cities that matter",
    citySub:
      "Not a radius map. These are cities where plans are actually listed. Jakarta decides more than Frankfurt.",
    cityProv: "providers",
    pkg: "plans",
    from: "from",
    hvUnknown: "Not disclosed",
    navCompare: "Compare",
    arenaKicker: "Provider comparison",
    arenaH1: "Do not compare every cloud. Find the relevant ones first.",
    tabSov: "Control & residency",
    tabOss: "Open technology",
    scopeAsean: "ASEAN headquarters",
    scoreSov: "Control & residency indicator",
    scoreOss: "Open-technology indicator",
    navMethod: "Methodology",
    bldgKicker: "Facility directory",
    bldgH1: "Where is the data centre, really?",
    bldgListed: "Verified facility name",
    mapSov: "Control & residency",
    aboutKicker: "About CloudinAsia",
    aboutH1: "Cloud in Asia helps people understand cloud before they buy cloud",
    aboutLede:
      "CloudinAsia is a media and ecosystem platform connecting people, knowledge, community, and opportunity in Asia’s cloud-technology industry.",
    arenaLede:
      "ASEAN-first, then a global baseline. Sort by control & residency, open technology, price, coverage, or capacity. The list is a shortlist to check, not a winner.",
    tabCost: "Price",
    tabCover: "Coverage",
    tabPerf: "Capacity",
    scopeAll: "All",
    colProvider: "Provider",
    colHq: "HQ",
    colHv: "Hypervisor",
    colMetric: "Note",
    colScore: "Score",
    scoreCost: "From (USD)",
    scoreCover: "DC locations",
    scorePerf: "Largest vCPU",
    empty: "No rows for this filter.",
    nShown: "shown",
    methKicker: "How we score",
    methH1: "Where do the scores come from?",
    methLede:
      "We do not sell rankings. Arena numbers come from the same database. Incomplete data means a lower score — that is a signal, not a penalty for sport.",
    methSovT: "Control & data-residency indicator (0–100)",
    methSov1: "+40 residency: an ASEAN DC city on an OK plan, or an official region-page city. Empty / Undisclosed / Not disclosed = 0",
    methSov2: "+25 legal control: HQ or legal entity in ASEAN",
    methSov3: "+15 extra: ASEAN legal home matches the plan’s stated DC country",
    methSov4: "+20 facility: a listed building with an official name",
    methSovNote:
      "A local brand with an Undisclosed DC is not automatically high. A US operator’s Jakarta rack is not 100: data may sit in ASEAN, legal control does not. Open hypervisors belong in the open-technology indicator, not here.",
    methOssT: "Open source (0–100)",
    methOss1: "+30 KVM / Proxmox / Xen hypervisor",
    methOss2: "+20 Docker or Kubernetes",
    methOss3: "+20 Ceph / OpenEBS / Longhorn / Rook storage",
    methOss4: "+15 stack marked open source",
    methOss5: "+15 open control plane (Proxmox, OpenStack, Virtualizor)",
    methOssNote:
      "An unstated hypervisor is treated as unproven, not a hard zero. Open source is preferred so you can inspect it, not because it is cheap.",
    methOtherT: "Price, coverage, capacity",
    methOther:
      "Price: estimated USD per month. Hourly list prices are converted as 24 hours × 31 days. Coverage: recorded DC cities. Capacity: largest vCPU and RAM on file. Compare inside ASEAN, not against Hetzner.",
    methLimitT: "Honest limits",
    methLimit:
      "Scores are still provisional. Some rows come from an older seed, not a fresh scrape. Pure Europe is out of the default view. Global hyperscalers appear only when you switch to All.",
    methLawT: "Country of origin vs rack location",
    methLaw:
      "ASEAN alone is not enough. Sovereignty risk follows the operator’s country, not just the DC city. US companies sit under the CLOUD Act and Patriot Act even with racks in Jakarta. Chinese operators sit under China’s cyber laws. The Arena pill is headquarters, not the sales region.",
    methGo: "See the ranking",
    provBack: "Back to Arena",
    provHq: "Headquarters",
    provLegal: "Jurisdiction",
    riskUs: "US CLOUD Act",
    riskCn: "China cyber law",
    provStack: "Stack",
    stackHv: "Hypervisor",
    stackOrch: "Orchestration",
    stackStor: "Storage",
    stackCp: "Control plane",
    stackRuntime: "Container runtime",
    provCities: "DC cities",
    provPlans: "Plans",
    provSov: "Control & residency",
    provOss: "Open source",
    colPlan: "Plan",
    colCpu: "vCPU",
    colRam: "RAM",
    colDisk: "Disk",
    colPrice: "Price",
    noPlans: "No plans in this database yet.",
    noProv: "Provider not found.",
    navMap: "Map",
    bldgLede:
      "Specific building names from public sources. Unlisted sites stay Unknown Building. Click to see providers inside.",
    bldgProviders: "Providers",
    bldgOperator: "Operator",
    bldgAddress: "Address",
    bldgInHere: "Providers in this building",
    bldgBack: "All buildings",
    mapKicker: "Map",
    mapH1: "Click a region",
    mapLede:
      "No pins. Click a country, then a city, to see who is there. Two modes: how crowded, and control & residency.",
    mapPop: "Provider density",
    mapHintPop: "Darker teal means more providers in that region.",
    mapHintSov: "Darker teal means a higher average control & residency score.",
    mapClick: "Click a country on the map.",
    mapCables: "Cables",
    mapProviders: "Providers here",
    mapCities: "Cities",
    mapNone: "No providers recorded in this region yet.",
    techKicker: "Technology",
    techH1: "Do not stop at the price. See what actually runs the cloud.",
    techLede:
      "Each page reviews one technology: what it is, trade-offs, then which providers and plans in this database mention it. Not a brand ad. Open source is preferred because it can be inspected.",
    techBack: "All technologies",
    techOpen: "Open",
    techClosed: "Closed",
    techLicence: "Licence",
    techWhat: "What it is",
    techPlus: "Strengths",
    techMinus: "Limits",
    techWho: "Providers that list this technology",
    techPlans: "Example plans",
    techProviders: "Providers",
    techNone: "No provider in this database lists this technology. We do not invent it.",
    about1t: "A rack here is not the same as data here",
    about1:
      "Law follows the company and its jurisdiction, not only the building address. The US Patriot Act and CLOUD Act still apply to US operators with machines in Singapore or Jakarta. China’s cyber laws apply to Chinese operators. PDP, PDPA and PDPD apply in their own countries. Comparing region prices alone is an easy way to choose badly.",
    about2t: "Open source so you can prove, not only trust",
    about2:
      "KVM, Xen, OpenStack, Ceph, Kubernetes, Docker, MinIO: the code can be reviewed. VMware, Hyper-V and closed panels are legitimate — but you depend on that vendor and its home country. We do not scorn closed software. We write down the consequence.",
    about3t: "Neutral, not empty of values",
    about3:
      "The ranking uses the same formula for everyone. We do not sell plans. The editorial stance is that data and control should sit closer to people and institutions in ASEAN, on a stack that can be inspected. That stance is stated here, not hidden inside the score.",
    about4t: "For all of ASEAN",
    about4:
      "Readers in Hanoi, Manila, Kuala Lumpur, Bangkok, Singapore, Phnom Penh, Vientiane, Naypyidaw, Bandar Seri Begawan and Jakarta live under different statutes. The shared questions are the same: operator country, DC building, and whether the stack is open. Then compare with data, not with slogans.",
    lawBanner:
      "This summary is an editorial primer, not legal advice. Your duties depend on data type, sector, contracting entity, processing purpose, subprocessors, and transfer tools. Check official sources and legal/compliance before a production decision.",
    lawReview: "Needs official-source verification and a review date.",
    bldgUnknownH1: "Facility location not yet verified",
    bldgUnknownSub: "A provider names this area, but the building, operator, or address cannot be confirmed from public sources.",
    bldgUnknownBody: "This record is kept so the gap stays visible. It does not claim the provider sits in a specific facility.",
    navCorrect: "Corrections",
    correctKicker: "Data corrections",
    correctH1: "Report a bad field or send new evidence",
    correctLede:
      "This directory is editorial. If a field is wrong, stale, or you have a primary source we have not used, send the evidence. We record corrections; we do not change data from an unsourced claim.",
    correctHow:
      "Include: provider or facility name, the field, a primary-source URL, the source date, and your organisation. Do not send customer data or trade secrets.",
    correctGo: "Open CloudinAsia",
    methVerT: "Formula version",
    methVer:
      "Formula 2026.08.18. Control indicator = data residency 40 · legal control 40 · named facility 20. Not a company-passport prize. Empty fields score 0, never minus. Open technology and evidence quality stay separate.",
    techVaried: "Varies",
    techCountNote: "Counts use fields the provider wrote; inferences are not counted.",
    lastUpdated: "Dataset reviewed 30 August 2026",
    updKicker: "Data log",
    updH1: "Cloud Directory updates",
    updLede:
      "Newly found providers, plus older providers whose public data just changed. Each entry shows the date and time in WIB. Prices and halls only when written on the official site.",
    updEmpty: "No update entries yet.",
    updNew: "Newly found",
    updChanged: "Data updated",
    scoreConf: "Evidence quality",
    evClaimed: "Provider-stated",
    evInferred: "Inferred",
    evUnknown: "Unknown",
    evVerified: "Verified",
    provEvidence: "Evidence status by field",
    fieldHq: "Headquarters",
    fieldHv: "Hypervisor",
    fieldSrc: "Public source",
    fieldBldg: "Named facility",
    fieldDc: "DC country on a plan",
    openSource: "Open source",
    methConfBody:
      "Evidence quality: headquarters 20 · stated hypervisor 20 / inferred 10 · named facility 15 · DC country on a plan 15 · source URL 15 · jurisdiction 15. Empty fields are not penalised.",
    navStart: "Start",
    startKicker: "First needs",
    startH1: "Tell us what you need from cloud",
    startLede: "You do not need every technical term. Answer what you know. If something is unclear, we turn it into a question you can take to your team or a provider.",
    startPrivacy: "Do not enter personal names, secrets, ID numbers or internal documents. Pick general categories only.",
    startResultGo: "See comparison focus",
    qOrg: "Which organisation is closest to yours?",
    qOrgHelp: "This only tunes the questions and checklist. It is not a legal assessment.",
    qWork: "What will you run in the cloud?",
    qWorkHelp: "Pick up to three. You do not need to describe the architecture.",
    qImpact: "If the service stops for a few hours, what happens?",
    qData: "Does this system store data that needs tighter care?",
    qDataHelp: "If unsure, pick not sure yet. We will add data classification to your checklist.",
    qCountry: "Where are most of your users and operations?",
    qPrio: "What matters most at this first stage? Pick up to three.",
    resultKicker: "Screening result",
    resultH1: "This is your comparison focus—not a final decision",
    resultPri: "Your priorities",
    resultUnk: "Still to be known",
    resultUnkNone: "No core answers were skipped.",
    resultVal: "To validate with the relevant team",
    resultCheck: "Questions for the provider",
    resultShort: "Shortlist to check",
    resultShortHelp: "2–4 candidates from your answers. Not a brand ranking and not a compliance certificate.",
    resultCompare: "Compare this shortlist",
    resultArena: "See the full list",
    resultEdit: "Change answers",
    resultClear: "Delete my answers",
    resultSaved: "Answers are stored on this device.",
    screenBanner: "This is a screening result, not a compliance assessment. Take the shortlist to legal/compliance, security, risk or procurement who know your sector and jurisdiction.",
    heroCta: "Start from the need",
    heroCta2: "I already know my criteria",
    conceptKicker: "Five ideas",
    conceptH2: "What to understand before provider names",
    concept1t: "Where is the data?",
    concept1: "Primary data, copies, backups and metadata can sit in different places. A server location alone does not prove security or compliance.",
    concept2t: "Who is the contracting party?",
    concept2: "The brand name and the company that signs the contract can differ.",
    concept3t: "Who can operate or access it?",
    concept3: "A local server does not always mean the whole management system is local.",
    concept4t: "What happens in an outage or if you leave?",
    concept4: "Check recovery, support, data format, APIs and exit cost.",
    concept5t: "What is the evidence, and how recent?",
    concept5: "Provider claims, primary sources, inferences and unknowns must be read differently.",
    whyShown: "Why this result appeared",
    needConfirm: "Needs confirming",
    addCompare: "Add to comparison",
    inCompare: "In comparison",
    compareNav: "Compare",
    compareH1: "Compare what is known—and what still needs asking",
    compareEmpty: "Pick 2–4 providers from the list. This is a shortlist to validate, not a final recommendation.",
    unknownHint: "Unknown does not mean bad or unavailable.",
    beginnerKnown: "What public sources can show",
    beginnerUnknown: "What is still unclear",
    ossPolicyH2: "Open source in ASEAN: what is verified, what is historical",
    ossPolicySub: "No ASEAN-wide OSS mandate was verified in the official sources reviewed. The useful question is which controls, evidence, contracts, data locations, support and exit plans you can show.",
    lawVnT: "Vietnam · Decree 13/2023/ND-CP",
    lawOssBadge: "Official sources reviewed 17 Aug 2026 · Status can change · Not a compliance ruling",
    bldgNoPhoto: "No verified public photo for this facility yet. We do not fill the gap with stock images.",
    bldgPhotoSrc: "Photo source",
    techOrigin: "Origin",
    techSteward: "Steward",
    techEnterprise: "Enterprise",
    techEntYes: "Yes",
    techEntNo: "No separate SKU",
    techEntIndirect: "Not sold separately",
    chipLocal: "Local ASEAN",
    chipGlobal: "Global",
    chipAsk: "Thin public evidence",
    footBlurb: "Cloud Directory helps compare providers, data locations, and stacks you can trace. Not a compliance certificate.",
    footExplore: "Explore",
    footAbout: "Editorial",
    footSource: "Open source",
    footGithub: "View on GitHub",
    footLicense: "Dataset and method can be reviewed. Pull requests and corrections welcome.",
    undisclosedBuilding: "Undisclosed building",
  },
} as const;

export type Copy = (typeof COPY)[Lang];
