import type { VerifiedFact } from "../src/intelligence/types.ts";
import { INTELLIGENCE_METHODOLOGY_ID } from "../src/intelligence/types.ts";

export const LONGITUDINAL_WINDOW = {
  start: "2025-01-01T00:00:00.000Z",
  end: "2026-01-01T00:00:00.000Z",
} as const;

export const LONGITUDINAL_DATA_REVISION = "drv-intel-2026-01";

export function makeFact(partial: Omit<VerifiedFact, "methodologyVersion" | "dataRevision" | "publishedAt"> & { publishedAt?: string }): VerifiedFact {
  return {
    methodologyVersion: INTELLIGENCE_METHODOLOGY_ID,
    dataRevision: LONGITUDINAL_DATA_REVISION,
    publishedAt: partial.publishedAt ?? partial.observedAt,
    verifiedAt: partial.publishedAt ?? partial.observedAt,
    ...partial,
  };
}

const fact = makeFact;

/** Synthetic 12-month ASEAN history. Fictional providers only. */
export function longitudinalFacts(): VerifiedFact[] {
  return [
    fact({
      receiptId: "r-a-id-1",
      revisionId: "rev-a-id-1",
      changeType: "create",
      entityType: "provider",
      entityId: "prov-a",
      fieldName: "country_presence",
      providerId: "prov-a",
      countryCode: "ID",
      observedAt: "2025-01-15T00:00:00.000Z",
      verificationState: "verified",
      knowledgeState: "present",
      afterValue: { countryCode: "ID" },
      beforeValue: null,
    }),
    fact({
      receiptId: "r-b-sg-1",
      revisionId: "rev-b-sg-1",
      changeType: "create",
      entityType: "provider",
      entityId: "prov-b",
      fieldName: "country_presence",
      providerId: "prov-b",
      countryCode: "SG",
      observedAt: "2025-02-10T00:00:00.000Z",
      verificationState: "verified",
      knowledgeState: "present",
      afterValue: { countryCode: "SG" },
      beforeValue: null,
    }),
    fact({
      receiptId: "r-a-off-1",
      revisionId: "rev-a-off-1",
      changeType: "create",
      entityType: "offering",
      entityId: "off-a1",
      fieldName: "offering",
      providerId: "prov-a",
      countryCode: "ID",
      observedAt: "2025-03-05T00:00:00.000Z",
      verificationState: "verified",
      knowledgeState: "present",
      afterValue: { name: "Small ID" },
      beforeValue: null,
    }),
    fact({
      receiptId: "r-a-price-1a",
      revisionId: "rev-a-price-1a",
      changeType: "create",
      entityType: "price",
      entityId: "off-a1",
      fieldName: "price",
      providerId: "prov-a",
      countryCode: "ID",
      observedAt: "2025-03-05T00:00:00.000Z",
      publishedAt: "2025-03-05T01:00:00.000Z",
      verificationState: "verified",
      knowledgeState: "present",
      afterValue: { amount: 9, currency: "USD" },
      beforeValue: null,
      comparable: true,
      amount: 9,
      currency: "USD",
      promo: false,
    }),
    fact({
      receiptId: "r-a-price-1b",
      revisionId: "rev-a-price-1b",
      changeType: "update",
      entityType: "price",
      entityId: "off-a1",
      fieldName: "price",
      providerId: "prov-a",
      countryCode: "ID",
      observedAt: "2025-03-20T00:00:00.000Z",
      publishedAt: "2025-03-20T01:00:00.000Z",
      verificationState: "verified",
      knowledgeState: "present",
      afterValue: { amount: 10, currency: "USD" },
      beforeValue: { amount: 9, currency: "USD" },
      comparable: true,
      amount: 10,
      currency: "USD",
      promo: false,
      supersedesReceiptId: "r-a-price-1a",
    }),
    fact({
      receiptId: "r-a-off-2",
      revisionId: "rev-a-off-2",
      changeType: "create",
      entityType: "offering",
      entityId: "off-a2",
      fieldName: "offering",
      providerId: "prov-a",
      countryCode: "ID",
      observedAt: "2025-04-08T00:00:00.000Z",
      verificationState: "verified",
      knowledgeState: "present",
      afterValue: { name: "Medium ID" },
      beforeValue: null,
    }),
    fact({
      receiptId: "r-a-price-2",
      revisionId: "rev-a-price-2",
      changeType: "create",
      entityType: "price",
      entityId: "off-a2",
      fieldName: "price",
      providerId: "prov-a",
      countryCode: "ID",
      observedAt: "2025-04-08T00:00:00.000Z",
      verificationState: "verified",
      knowledgeState: "present",
      afterValue: { amount: 12, currency: "USD" },
      beforeValue: null,
      comparable: true,
      amount: 12,
      currency: "USD",
      promo: false,
    }),
    fact({
      receiptId: "r-b-off-1",
      revisionId: "rev-b-off-1",
      changeType: "create",
      entityType: "offering",
      entityId: "off-b1",
      fieldName: "offering",
      providerId: "prov-b",
      countryCode: "SG",
      observedAt: "2025-03-12T00:00:00.000Z",
      verificationState: "verified",
      knowledgeState: "present",
      afterValue: { name: "SG Small" },
      beforeValue: null,
    }),
    fact({
      receiptId: "r-b-price-1",
      revisionId: "rev-b-price-1",
      changeType: "create",
      entityType: "price",
      entityId: "off-b1",
      fieldName: "price",
      providerId: "prov-b",
      countryCode: "SG",
      observedAt: "2025-03-12T00:00:00.000Z",
      verificationState: "verified",
      knowledgeState: "present",
      afterValue: { amount: 20, currency: "USD" },
      beforeValue: null,
      comparable: true,
      amount: 20,
      currency: "USD",
      promo: false,
    }),
    fact({
      receiptId: "r-a-fac-1",
      revisionId: "rev-a-fac-1",
      changeType: "create",
      entityType: "facility",
      entityId: "fac-a1",
      fieldName: "facility",
      providerId: "prov-a",
      countryCode: "ID",
      facilityId: "fac-a1",
      operatorId: "op-nusantara",
      observedAt: "2025-05-01T00:00:00.000Z",
      verificationState: "verified",
      knowledgeState: "present",
      afterValue: { name: "Jakarta Hall" },
      beforeValue: null,
    }),
    fact({
      receiptId: "r-a-tech-1",
      revisionId: "rev-a-tech-1",
      changeType: "create",
      entityType: "technology",
      entityId: "tech-kvm",
      fieldName: "technology",
      providerId: "prov-a",
      countryCode: "ID",
      technologySlug: "kvm",
      observedAt: "2025-06-01T00:00:00.000Z",
      verificationState: "verified",
      knowledgeState: "present",
      afterValue: { slug: "kvm" },
      beforeValue: null,
    }),
    fact({
      receiptId: "r-b-fac-1",
      revisionId: "rev-b-fac-1",
      changeType: "create",
      entityType: "facility",
      entityId: "fac-b1",
      fieldName: "facility",
      providerId: "prov-b",
      countryCode: "SG",
      facilityId: "fac-b1",
      operatorId: "op-sg",
      observedAt: "2025-06-15T00:00:00.000Z",
      verificationState: "verified",
      knowledgeState: "present",
      afterValue: { name: "SG Hall" },
      beforeValue: null,
    }),
    fact({
      receiptId: "r-a-price-1c",
      revisionId: "rev-a-price-1c",
      changeType: "update",
      entityType: "price",
      entityId: "off-a1",
      fieldName: "price",
      providerId: "prov-a",
      countryCode: "ID",
      observedAt: "2025-07-01T00:00:00.000Z",
      verificationState: "verified",
      knowledgeState: "present",
      afterValue: { amount: 11, currency: "USD" },
      beforeValue: { amount: 10, currency: "USD" },
      comparable: true,
      amount: 11,
      currency: "USD",
      promo: false,
      supersedesReceiptId: "r-a-price-1b",
    }),
    fact({
      receiptId: "r-a-off-2-retract",
      revisionId: "rev-a-off-2-retract",
      changeType: "retract",
      entityType: "offering",
      entityId: "off-a2",
      fieldName: "offering",
      providerId: "prov-a",
      countryCode: "ID",
      observedAt: "2025-08-01T00:00:00.000Z",
      verificationState: "verified",
      knowledgeState: "confirmed_absent",
      afterValue: null,
      beforeValue: { name: "Medium ID" },
    }),
    fact({
      receiptId: "r-a-price-2-retract",
      revisionId: "rev-a-price-2-retract",
      changeType: "retract",
      entityType: "price",
      entityId: "off-a2",
      fieldName: "price",
      providerId: "prov-a",
      countryCode: "ID",
      observedAt: "2025-08-01T00:00:00.000Z",
      verificationState: "verified",
      knowledgeState: "confirmed_absent",
      afterValue: null,
      beforeValue: { amount: 12, currency: "USD" },
      comparable: true,
    }),
    fact({
      receiptId: "r-b-fac-rollback",
      revisionId: "rev-b-fac-rollback",
      changeType: "rollback",
      entityType: "facility",
      entityId: "fac-b1",
      fieldName: "facility",
      providerId: "prov-b",
      countryCode: "SG",
      facilityId: "fac-b1",
      observedAt: "2025-09-01T00:00:00.000Z",
      verificationState: "verified",
      knowledgeState: "confirmed_absent",
      afterValue: null,
      beforeValue: { name: "SG Hall" },
      supersedesReceiptId: "r-b-fac-1",
    }),
    fact({
      receiptId: "r-a-conflict",
      revisionId: "rev-a-conflict",
      changeType: "update",
      entityType: "technology",
      entityId: "tech-kvm",
      fieldName: "technology",
      providerId: "prov-a",
      countryCode: "ID",
      technologySlug: "kvm",
      observedAt: "2025-09-10T00:00:00.000Z",
      verificationState: "verified",
      knowledgeState: "conflicting",
      afterValue: { slug: "kvm", note: "hedged" },
      beforeValue: { slug: "kvm" },
    }),
    fact({
      receiptId: "r-a-conflict-fix",
      revisionId: "rev-a-conflict-fix",
      changeType: "correction",
      entityType: "technology",
      entityId: "tech-kvm",
      fieldName: "technology",
      providerId: "prov-a",
      countryCode: "ID",
      technologySlug: "kvm",
      observedAt: "2025-10-05T00:00:00.000Z",
      verificationState: "verified",
      knowledgeState: "present",
      afterValue: { slug: "kvm" },
      beforeValue: { slug: "kvm", note: "hedged" },
    }),
    fact({
      receiptId: "r-a-stale-claim",
      revisionId: "rev-a-stale",
      changeType: "create",
      entityType: "evidence",
      entityId: "ev-stale",
      fieldName: "primary_residency",
      providerId: "prov-a",
      countryCode: "ID",
      observedAt: "2025-01-02T00:00:00.000Z",
      verificationState: "verified",
      knowledgeState: "present",
      afterValue: { country: "Indonesia" },
      beforeValue: null,
      validTo: "2025-11-15T00:00:00.000Z",
    }),
    fact({
      receiptId: "r-a-legal",
      revisionId: "rev-a-legal",
      changeType: "create",
      entityType: "evidence",
      entityId: "ev-legal",
      fieldName: "legal_entity",
      providerId: "prov-a",
      countryCode: "ID",
      observedAt: "2025-04-01T00:00:00.000Z",
      verificationState: "verified",
      knowledgeState: "present",
      afterValue: { jurisdictionCountry: "ID" },
      beforeValue: null,
    }),
    fact({
      receiptId: "r-a-price-ev",
      revisionId: "rev-a-price-ev",
      changeType: "create",
      entityType: "evidence",
      entityId: "ev-price",
      fieldName: "price",
      providerId: "prov-a",
      countryCode: "ID",
      observedAt: "2025-03-05T00:00:00.000Z",
      verificationState: "verified",
      knowledgeState: "present",
      afterValue: { amount: 10 },
      beforeValue: null,
    }),
    fact({
      receiptId: "r-a-sg-presence",
      revisionId: "rev-a-sg",
      changeType: "create",
      entityType: "provider",
      entityId: "prov-a",
      fieldName: "country_presence",
      providerId: "prov-a",
      countryCode: "SG",
      observedAt: "2025-12-01T00:00:00.000Z",
      verificationState: "verified",
      knowledgeState: "present",
      afterValue: { countryCode: "SG" },
      beforeValue: null,
    }),
    fact({
      receiptId: "r-pending",
      revisionId: "rev-pending",
      changeType: "create",
      entityType: "offering",
      entityId: "off-pending",
      fieldName: "offering",
      providerId: "prov-a",
      countryCode: "ID",
      observedAt: "2025-06-20T00:00:00.000Z",
      verificationState: "pending",
      knowledgeState: "present",
      afterValue: { name: "Unverified" },
      beforeValue: null,
    }),
    fact({
      receiptId: "r-promo",
      revisionId: "rev-promo",
      changeType: "create",
      entityType: "price",
      entityId: "off-promo",
      fieldName: "price",
      providerId: "prov-a",
      countryCode: "ID",
      observedAt: "2025-05-15T00:00:00.000Z",
      verificationState: "verified",
      knowledgeState: "present",
      afterValue: { amount: 1, currency: "USD" },
      beforeValue: null,
      comparable: false,
      amount: 1,
      currency: "USD",
      promo: true,
    }),
    fact({
      receiptId: "r-c-bn",
      revisionId: "rev-c-bn",
      changeType: "create",
      entityType: "provider",
      entityId: "prov-c",
      fieldName: "country_presence",
      providerId: "prov-c",
      countryCode: "BN",
      observedAt: "2025-04-20T00:00:00.000Z",
      verificationState: "verified",
      knowledgeState: "present",
      afterValue: { country: "Brunei" },
      beforeValue: null,
    }),
  ];
}

export function denseEligibleFacts(): VerifiedFact[] {
  const rows: VerifiedFact[] = [];
  for (let month = 0; month < 12; month += 1) {
    const observedAt = new Date(Date.UTC(2025, month, 8)).toISOString();
    const nProviders = 3 + Math.floor(month / 3);
    for (let i = 0; i < nProviders; i += 1) {
      rows.push(
        fact({
          receiptId: `dense-p-${month}-${i}`,
          revisionId: `dense-rev-p-${month}-${i}`,
          changeType: month === 0 ? "create" : "update",
          entityType: "provider",
          entityId: `dense-${i}`,
          fieldName: "country_presence",
          providerId: `dense-${i}`,
          countryCode: "ID",
          observedAt,
          verificationState: "verified",
          knowledgeState: "present",
          afterValue: { countryCode: "ID", n: nProviders },
          beforeValue: null,
        })
      );
      rows.push(
        fact({
          receiptId: `dense-o-${month}-${i}`,
          revisionId: `dense-rev-o-${month}-${i}`,
          changeType: month === 0 ? "create" : "update",
          entityType: "offering",
          entityId: `dense-off-${i}`,
          fieldName: "offering",
          providerId: `dense-${i}`,
          countryCode: "ID",
          observedAt,
          verificationState: "verified",
          knowledgeState: "present",
          afterValue: { name: `off-${i}` },
          beforeValue: null,
        })
      );
      rows.push(
        fact({
          receiptId: `dense-price-${month}-${i}`,
          revisionId: `dense-rev-price-${month}-${i}`,
          changeType: month === 0 ? "create" : "update",
          entityType: "price",
          entityId: `dense-off-${i}`,
          fieldName: "price",
          providerId: `dense-${i}`,
          countryCode: "ID",
          observedAt,
          verificationState: "verified",
          knowledgeState: "present",
          afterValue: { amount: 10 + month + i, currency: "USD" },
          beforeValue: null,
          comparable: true,
          amount: 10 + month + i,
          currency: "USD",
          promo: false,
        })
      );
    }
  }
  return rows;
}

/** Four comparable offerings whose prices alternate, so directional backtests fail. */
export function oscillatingPriceFacts(): VerifiedFact[] {
  const rows: VerifiedFact[] = [];
  for (let month = 0; month < 12; month += 1) {
    const observedAt = new Date(Date.UTC(2025, month, 8)).toISOString();
    const amount = month % 2 === 0 ? 10 : 20;
    for (let i = 0; i < 4; i += 1) {
      rows.push(
        fact({
          receiptId: `osc-p-${month}-${i}`,
          revisionId: `osc-rev-p-${month}-${i}`,
          changeType: month === 0 ? "create" : "update",
          entityType: "provider",
          entityId: `osc-${i}`,
          fieldName: "country_presence",
          providerId: `osc-${i}`,
          countryCode: "ID",
          observedAt,
          verificationState: "verified",
          knowledgeState: "present",
          afterValue: { countryCode: "ID" },
          beforeValue: null,
        })
      );
      rows.push(
        fact({
          receiptId: `osc-o-${month}-${i}`,
          revisionId: `osc-rev-o-${month}-${i}`,
          changeType: month === 0 ? "create" : "update",
          entityType: "offering",
          entityId: `osc-off-${i}`,
          fieldName: "offering",
          providerId: `osc-${i}`,
          countryCode: "ID",
          observedAt,
          verificationState: "verified",
          knowledgeState: "present",
          afterValue: { name: `osc-${i}` },
          beforeValue: null,
        })
      );
      rows.push(
        fact({
          receiptId: `osc-price-${month}-${i}`,
          revisionId: `osc-rev-price-${month}-${i}`,
          changeType: month === 0 ? "create" : "update",
          entityType: "price",
          entityId: `osc-off-${i}`,
          fieldName: "price",
          providerId: `osc-${i}`,
          countryCode: "ID",
          observedAt,
          verificationState: "verified",
          knowledgeState: "present",
          afterValue: { amount, currency: "USD" },
          beforeValue: null,
          comparable: true,
          amount,
          currency: "USD",
          promo: false,
        })
      );
    }
  }
  return rows;
}

/** Four comparable offerings with monotonically increasing prices (eligible + passing backtest). */
export function monotonicPriceFacts(): VerifiedFact[] {
  const rows: VerifiedFact[] = [];
  for (let month = 0; month < 12; month += 1) {
    const observedAt = new Date(Date.UTC(2025, month, 8)).toISOString();
    const amount = 10 + month;
    for (let i = 0; i < 4; i += 1) {
      rows.push(
        fact({
          receiptId: `mono-p-${month}-${i}`,
          revisionId: `mono-rev-p-${month}-${i}`,
          changeType: month === 0 ? "create" : "update",
          entityType: "provider",
          entityId: `mono-${i}`,
          fieldName: "country_presence",
          providerId: `mono-${i}`,
          countryCode: "ID",
          observedAt,
          verificationState: "verified",
          knowledgeState: "present",
          afterValue: { countryCode: "ID" },
          beforeValue: null,
        })
      );
      rows.push(
        fact({
          receiptId: `mono-o-${month}-${i}`,
          revisionId: `mono-rev-o-${month}-${i}`,
          changeType: month === 0 ? "create" : "update",
          entityType: "offering",
          entityId: `mono-off-${i}`,
          fieldName: "offering",
          providerId: `mono-${i}`,
          countryCode: "ID",
          observedAt,
          verificationState: "verified",
          knowledgeState: "present",
          afterValue: { name: `mono-${i}` },
          beforeValue: null,
        })
      );
      rows.push(
        fact({
          receiptId: `mono-price-${month}-${i}`,
          revisionId: `mono-rev-price-${month}-${i}`,
          changeType: month === 0 ? "create" : "update",
          entityType: "price",
          entityId: `mono-off-${i}`,
          fieldName: "price",
          providerId: `mono-${i}`,
          countryCode: "ID",
          observedAt,
          verificationState: "verified",
          knowledgeState: "present",
          afterValue: { amount, currency: "USD" },
          beforeValue: null,
          comparable: true,
          amount,
          currency: "USD",
          promo: false,
        })
      );
    }
  }
  return rows;
}
